### ISSUE TITLE
Ability to use TextCopy on Create

### ISSUE THREAD

**Issue by pritchard67** [sixlive/nova-text-copy-field#20]
I have a key (UUID) that is generated during the creation process that is hashed and never shown again.  I was hoping TextCopy would help me quickly add a copy icon, but it does not show on the create screen.  Am I missing a setting or is this not currently possible?

**Comment by sixlive** [comment]
It is currently not possible but I'm willing to implement it. I'll take a look later this week or this weekend!

**Comment by pritchard67** [comment]
That's awesome!  Thanks

**Comment by sixlive** [comment]
I ended up going down a rabbit hole trying to get this thing tested. I'll work on getting these couple open features merged and tagged over the next couple of days.

**Comment by pritchard67** [comment]
No worries.  I totally understand.  Not in a huge rush, but would be a nice
feature in my current project.

**Comment by sixlive** [comment]
@pritchard67 can you take a look at https://github.com/sixlive/nova-text-copy-field/pull/26 and make sure its what you are looking for?

**Comment by pritchard67** [comment]
I will try to take a look at this over the weekend.  Work has been
very busy.

**Comment by mikhailkozlov** [comment]
@sixlive I like it. Megre it!

**Comment by pritchard67** [comment]
Yes, this looks like what I am looking for.  Just the ability to copy a
field on the Nova create screen.

**Comment by bernhardh** [comment]
Maybe I am blind: On detail and index, everything works fine, but on the form field, nothing is show. This is my Field definition:

```php
TextCopy::make('Tag', function($item) {
    return '{{ diashow(' . $item->id . ',"u") }}';
})->showOnUpdating(true),
```

I am currently on `v1.5.0`:

```bash
$composer show | grep copy-field
sixlive/nova-text-copy-field                  v1.5.0             Laravel Nova text field with click to copy support
```

**Comment by bernhardh** [comment]
Ok, its because `ComputedField` aren't shown on forms (see `nova/ResolvesFields::removeNonUpdateFields`).

If I now use the other syntax:

```php
TextCopy::make('Tag')
    ->copyValue(function () {
        return '{{ diashow(' . $this->id . ',"u") }}';
    }),
```

it "works" somehow. It shows me an empty Input field with the copy icon. I can copy the correct value which I would expect. I can hide the input field by css, which would be OK, but I cant save the form, since Nova tries to store now the none existing field "tag" (since now its not a ComputedField anymore).

Edit:

Ok, if I add `->readonly(true)`, than it works. Kind of hacky, but it works.
